name: PersonalChest
version: '${project.version}'
main: com.github.e2318501.personalchest.PersonalChest
api-version: '1.19'
commands:
  personalchest:
    aliases: [ pc ]
    usage: |
      /<command> reload
